#!/usr/bin/env python3
"""Verify the declared release-package surface against Cargo's package list.

The package surface is a Rust release contract, not a Pillow-observable image
contract.  The fixture contains only declared input policy: the expected paths
and forbidden repository-only roots.  The package listing is generated by the
current Cargo invocation and is never committed as measured output.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tests" / "fixtures" / "package_surface_manifest.json"
PACKAGE_COMMAND = ["cargo", "package", "--allow-dirty", "--locked", "--list"]
TOP_LEVEL_KEYS = {
    "format_version",
    "scope",
    "assertion_origin",
    "package_command",
    "expected_files",
    "forbidden_prefixes",
}


def fail(message: str) -> None:
    raise RuntimeError(message)


def read_manifest() -> dict:
    try:
        value = json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read {MANIFEST}: {error}")
    if not isinstance(value, dict):
        fail(f"{MANIFEST} must contain a JSON object")
    return value


def strings(value: object, field: str) -> list[str]:
    if not isinstance(value, list) or not value:
        fail(f"{field} must be a non-empty string array")
    if any(not isinstance(item, str) or not item for item in value):
        fail(f"{field} must contain only non-empty strings")
    if len(set(value)) != len(value):
        fail(f"{field} must not contain duplicates")
    return value


def package_path(value: str, field: str) -> None:
    path = Path(value)
    if path.is_absolute() or ".." in path.parts or "\\" in value:
        fail(f"{field} must be a safe package-relative path: {value!r}")


def verify_manifest(document: dict) -> tuple[list[str], list[str]]:
    if set(document) != TOP_LEVEL_KEYS:
        fail(
            f"manifest keys differ: expected {sorted(TOP_LEVEL_KEYS)}, "
            f"got {sorted(document)}"
        )
    if document.get("format_version") != 1:
        fail("package surface manifest format_version must be 1")
    if document.get("scope") != "release_package_surface_v1":
        fail("package surface manifest scope must be release_package_surface_v1")
    if document.get("assertion_origin") != "release_package_contract":
        fail("package surface manifest must be release_package_contract evidence")
    if document.get("package_command") != PACKAGE_COMMAND:
        fail("package_command must be the approved Cargo package-list command")

    expected = strings(document.get("expected_files"), "expected_files")
    if expected != sorted(expected):
        fail("expected_files must be sorted for deterministic review")
    for path in expected:
        package_path(path, "expected_files entry")

    forbidden = strings(document.get("forbidden_prefixes"), "forbidden_prefixes")
    if forbidden != sorted(forbidden):
        fail("forbidden_prefixes must be sorted for deterministic review")
    for prefix in forbidden:
        package_path(prefix, "forbidden_prefixes entry")
        if not prefix.endswith("/"):
            fail(f"forbidden prefix must end with '/': {prefix!r}")
    for path in expected:
        if any(path.startswith(prefix) for prefix in forbidden):
            fail(f"expected package path is forbidden by the manifest: {path}")
    return expected, forbidden


def cargo_package_paths() -> list[str]:
    try:
        result = subprocess.run(
            PACKAGE_COMMAND,
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
            timeout=300,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        fail(f"Cargo package-list command did not complete: {error}")
    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip()
        fail(f"Cargo package-list command failed ({result.returncode}): {detail}")

    paths = [line.strip() for line in result.stdout.splitlines() if line.strip()]
    if len(paths) != len(set(paths)):
        fail("Cargo package-list command returned duplicate paths")
    for path in paths:
        package_path(path, "Cargo package-list path")
    return sorted(paths)


def verify() -> int:
    expected, forbidden = verify_manifest(read_manifest())
    actual = cargo_package_paths()
    expected_set = set(expected)
    actual_set = set(actual)
    missing = sorted(expected_set - actual_set)
    unexpected = sorted(actual_set - expected_set)
    if missing or unexpected:
        fail(f"package surface drift: missing={missing}, unexpected={unexpected}")
    forbidden_paths = [
        path for path in actual if any(path.startswith(prefix) for prefix in forbidden)
    ]
    if forbidden_paths:
        fail(f"package contains forbidden repository-only paths: {forbidden_paths}")
    return len(actual)


def main() -> int:
    try:
        count = verify()
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(
        f"package surface OK: {count} exact Cargo paths; "
        "repository-only roots remain excluded"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
